global:
  domain: "c-36f5be2.kyma.ondemand.com"
  imagePullSecret:
    {}
srv:
  bindings:
    db:
      serviceInstanceName: hana
    auth:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: 'destination'
  image:
    repository: abhianuj10/incident-management-srv
    tag: v0.0.1
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /health
    readiness:
      path: /health
hana-deployer:
  image:
    repository: abhianuj10/incident-management-hana-deployer
    tag: v0.0.1
  bindings:
    hana:
      serviceInstanceName: hana
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
hana:
  serviceOfferingName: hana
  servicePlanName: hdi-shared
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: incidents
    tenant-mode: dedicated
    oauth2-configuration:
      redirect-uris:
        - https://*.c-36f5be2.kyma.ondemand.com/**
destination:
  serviceOfferingName: 'destination'
  servicePlanName: 'lite'
  parameters:
    version: '1.0.0'
    HTML5Runtime_enabled: true
html5-apps-repo-host:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-host
html5-apps-deployer:
  env:
    SAP_CLOUD_SERVICE: incidents
  image:
    repository: "abhianuj10/incident-management-html5-deployer"
    tag: v0.0.1
  bindings:
    xsuaa:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: destination
    html5-apps-repo:
      serviceInstanceName: html5-apps-repo-host
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-html5-apps-deployer-configmap"
backendDestinations:
  srv-api:
    service: srv
